### ISSUE TITLE
Fails to run after initial install - Test failedkey

### ISSUE THREAD

**Issue by davidhanna66** [MicrosoftTranslator/DocumentTranslation#40] opened 2021-06-28 17:57 UTC
After installing and adding configurations, app closed twice after clicking Save and Test. Now I have entered service key, region, endpoint and I am receiving error Test failedkey. I have entered values as described in docs.

**Comment by chriswendt1** [comment] 2021-06-28 21:08
Thanks for the report.
Could it be that the key is for a different region than selected, or for a different resource? Needs to be for a Translator resource, not one for Cognitive Services. 
If region and resource are correct, can you tell me which region?

Also, when the app terminated, did you see the call stack?

**Comment by davidhanna66** [comment] 2021-06-28 21:14
Hi Chris- Hope you are doing well.

The key was from EUS2. I even put storage account there just in case.

I did not see call stack.

***@***.******@***.***D76C41.17CCF0E0]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by chriswendt1** [comment] 2021-06-28 21:26
OK, thanks. Let me try EUS2 and see what the problem is...
If you need a quick resolution, try "Global", if you can.

**Comment by chriswendt1** [comment] 2021-06-28 21:47
I can repro the problem.

**Comment by chriswendt1** [comment] 2021-06-28 22:07
Document Translation will work regardless. Text translation will fail for anything but "Global". Easy fix. Fixing...
Other problems:  When attempting text translation, the error appears in the result. Expected: status bar.
I would not repro the unexpected application exit.

**Comment by chriswendt1** [comment] 2021-07-04 02:08
Fixed in version 0.7.0.3 Let me know how it goes.

**Closed by chriswendt1** 2021-07-04 02:08 UTC

**Comment by chriswendt1** [comment] 2021-07-06 00:39
Updated binary as release 0.2.0.4.

**Comment by chriswendt1** [comment] 2021-07-07 20:54
Hi @davidhanna66 , can you let me know whether this fixed your issue? Are you unblocked now?
